// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Comment struct {
	CommentID string         `json:"comment_id"`
	Text      string         `json:"text"`
	CreatedAt time.Time      `json:"created_at"`
	UserID    string         `json:"user_id"`
	ImageID   sql.NullString `json:"image_id"`
	PostID    string         `json:"post_id"`
}

type Image struct {
	ImageID  string `json:"image_id"`
	FilePath string `json:"file_path"`
}

type Post struct {
	PostID     string         `json:"post_id"`
	Title      string         `json:"title"`
	Text       string         `json:"text"`
	CreatedAt  time.Time      `json:"created_at"`
	SuboliveID string         `json:"subolive_id"`
	UserID     string         `json:"user_id"`
	ImageID    sql.NullString `json:"image_id"`
}

type Subolife struct {
	SuboliveID string `json:"subolive_id"`
	Name       string `json:"name"`
}

type User struct {
	UserID   string `json:"user_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
}
