// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Comment struct {
	CommentID int32
	Text      string
	CreatedAt time.Time
	UserID    int32
	ImageID   sql.NullInt32
	PostID    int32
}

type Image struct {
	ImageID  int32
	FilePath string
}

type Post struct {
	PostID     int32
	Title      string
	Text       string
	CreatedAt  time.Time
	SuboliveID int32
	UserID     int32
	ImageID    sql.NullInt32
}

type Subolife struct {
	SuboliveID int32
	Name       string
}

type User struct {
	UserID   int32
	Email    string
	Username string
	Password string
}
